from simple_image_download import simple_image_download as simp

# create a new class instance

response = simp.simple_image_download

keyword = [
            "Mussel",
            "Scallop",
            "Oyster",
            "Cod",
            "Pollock",
            "Fishcake",
            "Fish",
            "Surimi",
            "Tofu",
            "Fried tofu",
            "Tempeh",
            "Spam",
            "Anchovy broth pack",
            "Rice",
            "Cooked rice",
            "Brown rice",
            "Barley",
            "Millet",
            "Quinoa",
            "Oats",
            "Bread",
            "Bagel",
            "Pasta",
            "Spaghetti",
            "Noodles",
            "Udon",
            "Ramen",
            "Soba",
            "Vermicelli",
            "Rice cake",
            "Tortilla",
            "Flour",
            "Corn flour",
            "Breadcrumbs",
            "Cereal",
            "Granola",
            "Pepper",
            "Ketchup",
            "Mayonnaise",
            "Soy sauce",
            "Gochujang",
            "Doenjang",
            "Vinegar",
            "Sesame oil",
            "Olive oil",
            "Canola oil",
            "Honey",
            "Jam",
            "Peanut butter",
            "Miso",
            "Apple",
            "Pear",
            "Banana",
            "grape",
            "Strawberry",
            "Blueberry",
            "Raspberry",
            "Cherry",
            "Peach",
            "White peach",
            "Nectarine",
            "Plum",
            "Apricot",
            "Persimmon",
            "Pineapple",
            "Watermelon",
            "Melon",
            "Cantaloupe",
            "Papaya",
            "Mango",
            "Orange",
            "Tangerine",
            "Mandarin",
            "Lemon",
            "Lime",
            "Grapefruit",
            "Avocado",
            "Kiwi",
            "Pomegranate",
            "Coconut",
            "Fig",
            "Mulberry",
            "Olive",
            "Currant",
            "Quince",
            "Jujube",
            "Loquat",
            "Soursop"
           ]
for kw in keyword:
    # response().download(kw, 200)
    response().download(f"{kw} ingredient", 200)